// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: books.sql

package database

import (
	"context"
	"time"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (
  id, created_at, updated_at, title, content
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, created_at, updated_at, title, content
`

type CreateBookParams struct {
	ID        interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	Content   string
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Content,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Content,
	)
	return i, err
}

const getAllBooks = `-- name: GetAllBooks :many
SELECT id, created_at, updated_at, title, content FROM books
`

func (q *Queries) GetAllBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getAllBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, created_at, updated_at, title, content FROM books
WHERE id = ?
`

func (q *Queries) GetBookByID(ctx context.Context, id interface{}) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Content,
	)
	return i, err
}

const getContentByID = `-- name: GetContentByID :one
SELECT content FROM books
WHERE id = ?
`

func (q *Queries) GetContentByID(ctx context.Context, id interface{}) (string, error) {
	row := q.db.QueryRowContext(ctx, getContentByID, id)
	var content string
	err := row.Scan(&content)
	return content, err
}

const getContentByTitle = `-- name: GetContentByTitle :one
SELECT content FROM books
WHERE title = ?
`

func (q *Queries) GetContentByTitle(ctx context.Context, title string) (string, error) {
	row := q.db.QueryRowContext(ctx, getContentByTitle, title)
	var content string
	err := row.Scan(&content)
	return content, err
}
