// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Book struct {
	ID        interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
}
