
# python wrapper for package github.com/pat955/poki_books/internal/database within overall package database
# This is what you import to use the package.
# File is generated by gopy. Do not edit.
# gopy build -output=gopy -vm=python3 ../internal/database

# the following is required to enable dlopen to open the _go.so file
import os,sys,inspect,collections
try:
	import collections.abc as _collections_abc
except ImportError:
	_collections_abc = collections

cwd = os.getcwd()
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
os.chdir(currentdir)
from . import _database
from . import go

os.chdir(cwd)

# to use this code in your end-user python file, import it as follows:
# from database import database
# and then refer to everything using database. prefix
# packages imported by this package listed below:




# ---- Types ---

# Python type for slice []*sql.ColumnType
class Slice_Ptr_sql_ColumnType(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameter is a python list that we copy from
		"""
		self.index = 0
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_database.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_database.IncRef(self.handle)
		else:
			self.handle = _database.Slice_Ptr_sql_ColumnType_CTor()
			_database.IncRef(self.handle)
			if len(args) > 0:
				if not isinstance(args[0], _collections_abc.Iterable):
					raise TypeError('Slice_Ptr_sql_ColumnType.__init__ takes a sequence as argument')
				for elt in args[0]:
					self.append(elt)
	def __del__(self):
		_database.DecRef(self.handle)
	def __str__(self):
		s = 'database.Slice_Ptr_sql_ColumnType len: ' + str(len(self)) + ' handle: ' + str(self.handle) + ' ['
		if len(self) < 120:
			s += ', '.join(map(str, self)) + ']'
		return s
	def __repr__(self):
		return 'database.Slice_Ptr_sql_ColumnType([' + ', '.join(map(str, self)) + '])'
	def __len__(self):
		return _database.Slice_Ptr_sql_ColumnType_len(self.handle)
	def __getitem__(self, key):
		if isinstance(key, slice):
			if key.step == None or key.step == 1:
				st = key.start
				ed = key.stop
				if st == None:
					st = 0
				if ed == None:
					ed = _database.Slice_Ptr_sql_ColumnType_len(self.handle)
				return Slice_Ptr_sql_ColumnType(handle=_database.Slice_Ptr_sql_ColumnType_subslice(self.handle, st, ed))
			return [self[ii] for ii in range(*key.indices(len(self)))]
		elif isinstance(key, int):
			if key < 0:
				key += len(self)
			if key < 0 or key >= len(self):
				raise IndexError('slice index out of range')
			return go.Ptr_sql_ColumnType(handle=_database.Slice_Ptr_sql_ColumnType_elem(self.handle, key))
		else:
			raise TypeError('slice index invalid type')
	def __setitem__(self, idx, value):
		if idx < 0:
			idx += len(self)
		if idx < len(self):
			_database.Slice_Ptr_sql_ColumnType_set(self.handle, idx, value.handle)
			return
		raise IndexError('slice index out of range')
	def __iadd__(self, value):
		if not isinstance(value, _collections_abc.Iterable):
			raise TypeError('Slice_Ptr_sql_ColumnType.__iadd__ takes a sequence as argument')
		for elt in value:
			self.append(elt)
		return self
	def __iter__(self):
		self.index = 0
		return self
	def __next__(self):
		if self.index < len(self):
			rv = go.Ptr_sql_ColumnType(handle=_database.Slice_Ptr_sql_ColumnType_elem(self.handle, self.index))
			self.index = self.index + 1
			return rv
		raise StopIteration
	def append(self, value):
		_database.Slice_Ptr_sql_ColumnType_append(self.handle, value.handle)
	def copy(self, src):
		""" copy emulates the go copy function, copying elements into this list from source list, up to min of size of each list """
		mx = min(len(self), len(src))
		for i in range(mx):
			self[i] = src[i]

# Python type for slice []any
class Slice_any(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameter is a python list that we copy from
		"""
		self.index = 0
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_database.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_database.IncRef(self.handle)
		else:
			self.handle = _database.Slice_any_CTor()
			_database.IncRef(self.handle)
			if len(args) > 0:
				if not isinstance(args[0], _collections_abc.Iterable):
					raise TypeError('Slice_any.__init__ takes a sequence as argument')
				for elt in args[0]:
					self.append(elt)
	def __del__(self):
		_database.DecRef(self.handle)
	def __str__(self):
		s = 'database.Slice_any len: ' + str(len(self)) + ' handle: ' + str(self.handle) + ' ['
		if len(self) < 120:
			s += ', '.join(map(str, self)) + ']'
		return s
	def __repr__(self):
		return 'database.Slice_any([' + ', '.join(map(str, self)) + '])'
	def __len__(self):
		return _database.Slice_any_len(self.handle)
	def __getitem__(self, key):
		if isinstance(key, slice):
			if key.step == None or key.step == 1:
				st = key.start
				ed = key.stop
				if st == None:
					st = 0
				if ed == None:
					ed = _database.Slice_any_len(self.handle)
				return Slice_any(handle=_database.Slice_any_subslice(self.handle, st, ed))
			return [self[ii] for ii in range(*key.indices(len(self)))]
		elif isinstance(key, int):
			if key < 0:
				key += len(self)
			if key < 0 or key >= len(self):
				raise IndexError('slice index out of range')
			return any(handle=_database.Slice_any_elem(self.handle, key))
		else:
			raise TypeError('slice index invalid type')
	def __setitem__(self, idx, value):
		if idx < 0:
			idx += len(self)
		if idx < len(self):
			_database.Slice_any_set(self.handle, idx, value.handle)
			return
		raise IndexError('slice index out of range')
	def __iadd__(self, value):
		if not isinstance(value, _collections_abc.Iterable):
			raise TypeError('Slice_any.__iadd__ takes a sequence as argument')
		for elt in value:
			self.append(elt)
		return self
	def __iter__(self):
		self.index = 0
		return self
	def __next__(self):
		if self.index < len(self):
			rv = any(handle=_database.Slice_any_elem(self.handle, self.index))
			self.index = self.index + 1
			return rv
		raise StopIteration
	def append(self, value):
		_database.Slice_any_append(self.handle, value.handle)
	def copy(self, src):
		""" copy emulates the go copy function, copying elements into this list from source list, up to min of size of each list """
		mx = min(len(self), len(src))
		for i in range(mx):
			self[i] = src[i]

# Python type for slice []database.Book
class Slice_database_Book(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameter is a python list that we copy from
		"""
		self.index = 0
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_database.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_database.IncRef(self.handle)
		else:
			self.handle = _database.Slice_database_Book_CTor()
			_database.IncRef(self.handle)
			if len(args) > 0:
				if not isinstance(args[0], _collections_abc.Iterable):
					raise TypeError('Slice_database_Book.__init__ takes a sequence as argument')
				for elt in args[0]:
					self.append(elt)
	def __del__(self):
		_database.DecRef(self.handle)
	def __str__(self):
		s = 'database.Slice_database_Book len: ' + str(len(self)) + ' handle: ' + str(self.handle) + ' ['
		if len(self) < 120:
			s += ', '.join(map(str, self)) + ']'
		return s
	def __repr__(self):
		return 'database.Slice_database_Book([' + ', '.join(map(str, self)) + '])'
	def __len__(self):
		return _database.Slice_database_Book_len(self.handle)
	def __getitem__(self, key):
		if isinstance(key, slice):
			if key.step == None or key.step == 1:
				st = key.start
				ed = key.stop
				if st == None:
					st = 0
				if ed == None:
					ed = _database.Slice_database_Book_len(self.handle)
				return Slice_database_Book(handle=_database.Slice_database_Book_subslice(self.handle, st, ed))
			return [self[ii] for ii in range(*key.indices(len(self)))]
		elif isinstance(key, int):
			if key < 0:
				key += len(self)
			if key < 0 or key >= len(self):
				raise IndexError('slice index out of range')
			return Book(handle=_database.Slice_database_Book_elem(self.handle, key))
		else:
			raise TypeError('slice index invalid type')
	def __setitem__(self, idx, value):
		if idx < 0:
			idx += len(self)
		if idx < len(self):
			_database.Slice_database_Book_set(self.handle, idx, value.handle)
			return
		raise IndexError('slice index out of range')
	def __iadd__(self, value):
		if not isinstance(value, _collections_abc.Iterable):
			raise TypeError('Slice_database_Book.__iadd__ takes a sequence as argument')
		for elt in value:
			self.append(elt)
		return self
	def __iter__(self):
		self.index = 0
		return self
	def __next__(self):
		if self.index < len(self):
			rv = Book(handle=_database.Slice_database_Book_elem(self.handle, self.index))
			self.index = self.index + 1
			return rv
		raise StopIteration
	def append(self, value):
		_database.Slice_database_Book_append(self.handle, value.handle)
	def copy(self, src):
		""" copy emulates the go copy function, copying elements into this list from source list, up to min of size of each list """
		mx = min(len(self), len(src))
		for i in range(mx):
			self[i] = src[i]

# Python type for slice []interface{}
class Slice_interface_(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameter is a python list that we copy from
		"""
		self.index = 0
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_database.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_database.IncRef(self.handle)
		else:
			self.handle = _database.Slice_interface__CTor()
			_database.IncRef(self.handle)
			if len(args) > 0:
				if not isinstance(args[0], _collections_abc.Iterable):
					raise TypeError('Slice_interface_.__init__ takes a sequence as argument')
				for elt in args[0]:
					self.append(elt)
	def __del__(self):
		_database.DecRef(self.handle)
	def __str__(self):
		s = 'database.Slice_interface_ len: ' + str(len(self)) + ' handle: ' + str(self.handle) + ' ['
		if len(self) < 120:
			s += ', '.join(map(str, self)) + ']'
		return s
	def __repr__(self):
		return 'database.Slice_interface_([' + ', '.join(map(str, self)) + '])'
	def __len__(self):
		return _database.Slice_interface__len(self.handle)
	def __getitem__(self, key):
		if isinstance(key, slice):
			if key.step == None or key.step == 1:
				st = key.start
				ed = key.stop
				if st == None:
					st = 0
				if ed == None:
					ed = _database.Slice_interface__len(self.handle)
				return Slice_interface_(handle=_database.Slice_interface__subslice(self.handle, st, ed))
			return [self[ii] for ii in range(*key.indices(len(self)))]
		elif isinstance(key, int):
			if key < 0:
				key += len(self)
			if key < 0 or key >= len(self):
				raise IndexError('slice index out of range')
			return _database.Slice_interface__elem(self.handle, key)
		else:
			raise TypeError('slice index invalid type')
	def __setitem__(self, idx, value):
		if idx < 0:
			idx += len(self)
		if idx < len(self):
			_database.Slice_interface__set(self.handle, idx, value)
			return
		raise IndexError('slice index out of range')
	def __iadd__(self, value):
		if not isinstance(value, _collections_abc.Iterable):
			raise TypeError('Slice_interface_.__iadd__ takes a sequence as argument')
		for elt in value:
			self.append(elt)
		return self
	def __iter__(self):
		self.index = 0
		return self
	def __next__(self):
		if self.index < len(self):
			rv = _database.Slice_interface__elem(self.handle, self.index)
			self.index = self.index + 1
			return rv
		raise StopIteration
	def append(self, value):
		_database.Slice_interface__append(self.handle, value)
	def copy(self, src):
		""" copy emulates the go copy function, copying elements into this list from source list, up to min of size of each list """
		mx = min(len(self), len(src))
		for i in range(mx):
			self[i] = src[i]


#---- Enums from Go (collections of consts with same type) ---


#---- Constants from Go: Python can only ask that you please don't change these! ---


# ---- Global Variables: can only use functions to access ---


# ---- Interfaces ---

# Python type for interface database.DBTX
class DBTX(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		"""
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_database.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_database.IncRef(self.handle)
		else:
			self.handle = 0
	def ExecContext(self, arg_0, arg_1, *args):
		"""ExecContext(object, str, []str) object, str"""
		arg_2 = Slice_interface_(args)
		return go.sql_Result(handle=_database.database_DBTX_ExecContext(self.handle, arg_0.handle, arg_1, arg_2.handle))
	def PrepareContext(self, arg_0, arg_1):
		"""PrepareContext(object, str) object, str"""
		return go.Ptr_sql_Stmt(handle=_database.database_DBTX_PrepareContext(self.handle, arg_0.handle, arg_1))
	def QueryContext(self, arg_0, arg_1, *args):
		"""QueryContext(object, str, []str) object, str"""
		arg_2 = Slice_interface_(args)
		return go.Ptr_sql_Rows(handle=_database.database_DBTX_QueryContext(self.handle, arg_0.handle, arg_1, arg_2.handle))
	def QueryRowContext(self, arg_0, arg_1, *args):
		"""QueryRowContext(object, str, []str) object"""
		arg_2 = Slice_interface_(args)
		return go.Ptr_sql_Row(handle=_database.database_DBTX_QueryRowContext(self.handle, arg_0.handle, arg_1, arg_2.handle))


# ---- Structs ---

# Python type for struct database.CreateBookParams
class CreateBookParams(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameters can be unnamed in order of field names or named fields
		in which case a new Go object is constructed first
		"""
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_database.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_database.IncRef(self.handle)
		else:
			self.handle = _database.database_CreateBookParams_CTor()
			_database.IncRef(self.handle)
			if  1 < len(args):
				self.Title = args[1]
			if "Title" in kwargs:
				self.Title = kwargs["Title"]
			if  2 < len(args):
				self.Content = args[2]
			if "Content" in kwargs:
				self.Content = kwargs["Content"]
	def __del__(self):
		_database.DecRef(self.handle)
	def __str__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'database.CreateBookParams{'
		first = True
		for v in pr:
			if callable(v[1]):
				continue
			if first:
				first = False
			else:
				sv += ', '
			sv += v[0] + '=' + str(v[1])
		return sv + '}'
	def __repr__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'database.CreateBookParams ( '
		for v in pr:
			if not callable(v[1]):
				sv += v[0] + '=' + str(v[1]) + ', '
		return sv + ')'
	@property
	def Title(self):
		return _database.database_CreateBookParams_Title_Get(self.handle)
	@Title.setter
	def Title(self, value):
		if isinstance(value, go.GoClass):
			_database.database_CreateBookParams_Title_Set(self.handle, value.handle)
		else:
			_database.database_CreateBookParams_Title_Set(self.handle, value)
	@property
	def Content(self):
		return _database.database_CreateBookParams_Content_Get(self.handle)
	@Content.setter
	def Content(self, value):
		if isinstance(value, go.GoClass):
			_database.database_CreateBookParams_Content_Set(self.handle, value.handle)
		else:
			_database.database_CreateBookParams_Content_Set(self.handle, value)

# Python type for struct database.Queries
class Queries(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameters can be unnamed in order of field names or named fields
		in which case a new Go object is constructed first
		"""
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_database.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_database.IncRef(self.handle)
		else:
			self.handle = _database.database_Queries_CTor()
			_database.IncRef(self.handle)
	def __del__(self):
		_database.DecRef(self.handle)
	def __str__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'database.Queries{'
		first = True
		for v in pr:
			if callable(v[1]):
				continue
			if first:
				first = False
			else:
				sv += ', '
			sv += v[0] + '=' + str(v[1])
		return sv + '}'
	def __repr__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'database.Queries ( '
		for v in pr:
			if not callable(v[1]):
				sv += v[0] + '=' + str(v[1]) + ', '
		return sv + ')'
	def CreateBook(self, ctx, arg):
		"""CreateBook(object ctx, object arg) object, str"""
		return Book(handle=_database.database_Queries_CreateBook(self.handle, ctx.handle, arg.handle))
	def GetAllBooks(self, ctx):
		"""GetAllBooks(object ctx) []object, str"""
		return Slice_database_Book(handle=_database.database_Queries_GetAllBooks(self.handle, ctx.handle))
	def GetBookByID(self, ctx, id):
		"""GetBookByID(object ctx, str id) object, str"""
		return Book(handle=_database.database_Queries_GetBookByID(self.handle, ctx.handle, id))
	def GetContentByID(self, ctx, id):
		"""GetContentByID(object ctx, str id) str, str"""
		return _database.database_Queries_GetContentByID(self.handle, ctx.handle, id)
	def GetContentByTitle(self, ctx, title):
		"""GetContentByTitle(object ctx, str title) str, str"""
		return _database.database_Queries_GetContentByTitle(self.handle, ctx.handle, title)
	def WithTx(self, tx):
		"""WithTx(object tx) object"""
		return Queries(handle=_database.database_Queries_WithTx(self.handle, tx.handle))

# Python type for struct database.Book
class Book(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameters can be unnamed in order of field names or named fields
		in which case a new Go object is constructed first
		"""
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_database.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_database.IncRef(self.handle)
		else:
			self.handle = _database.database_Book_CTor()
			_database.IncRef(self.handle)
			if  1 < len(args):
				self.Title = args[1]
			if "Title" in kwargs:
				self.Title = kwargs["Title"]
			if  2 < len(args):
				self.Content = args[2]
			if "Content" in kwargs:
				self.Content = kwargs["Content"]
	def __del__(self):
		_database.DecRef(self.handle)
	def __str__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'database.Book{'
		first = True
		for v in pr:
			if callable(v[1]):
				continue
			if first:
				first = False
			else:
				sv += ', '
			sv += v[0] + '=' + str(v[1])
		return sv + '}'
	def __repr__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'database.Book ( '
		for v in pr:
			if not callable(v[1]):
				sv += v[0] + '=' + str(v[1]) + ', '
		return sv + ')'
	@property
	def Title(self):
		return _database.database_Book_Title_Get(self.handle)
	@Title.setter
	def Title(self, value):
		if isinstance(value, go.GoClass):
			_database.database_Book_Title_Set(self.handle, value.handle)
		else:
			_database.database_Book_Title_Set(self.handle, value)
	@property
	def Content(self):
		return _database.database_Book_Content_Get(self.handle)
	@Content.setter
	def Content(self, value):
		if isinstance(value, go.GoClass):
			_database.database_Book_Content_Set(self.handle, value.handle)
		else:
			_database.database_Book_Content_Set(self.handle, value)


# ---- Slices ---


# ---- Maps ---


# ---- Constructors ---
def New(db):
	"""New(object db) object"""
	return Queries(handle=_database.database_New(db.handle))


# ---- Functions ---


