name: ci

on:
  push:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
    
      - name: Install pip
        run: python -m pip install --upgrade pip
  
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover -s ./src/ -p 'test_*.py'
        
      - name: Install bandit
        run: pip install bandit
      
      - name: Check for security issues
        run: bandit -r .

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pylint
        run: pip install pylint
      
      - name: Linting, errors
        run: pylint ./src/*.py -E